### ISSUE TITLE
Register Connection Issue

### ISSUE THREAD

**Issue by serbancosmincst** [wojtkowiak/meteor-direct-stream-access#7]
Hi,

I recently started to use this package https://github.com/cult-of-coders in order to replace mongodb oplog. As soon as i added this, i got errors from DirectStreamAccess.client.js regarding more than one onMessage handler ( line 72).  Would it be possible to remove that check?

P.S. I am using another package : https://github.com/wojtkowiak/meteor-custom-protocol , which list this as a dependency.

Thank you.

**Comment by wojtkowiak** [comment]
Is this still a case for you? This would only happen if you somehow had two different versions of direct stream access in the project.
I do not think any of packages from `cult-of-coders` are using direct stream access. 
Could you post your `.meteor/versions`?
